export const GET_PRODUCTS_DATA = 'GET_PRODUCTS_DATA';
export const GET_PRODUCTS_DATA_SUCCESS = 'GET_PRODUCTS_DATA_SUCCESS';
export const GET_PRODUCTS_DATA_FAILURE = 'GET_PRODUCTS_DATA_FAILURE';

export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILURE = 'GET_PRODUCT_DETAIL_FAILURE';


export const GET_RANDOM_IMAGE = 'GET_RANDOM_IMAGE';
export const GET_RANDOM_IMAGE_SUCCESS = 'GET_RANDOM_IMAGE_SUCCESS';
export const GET_RANDOM_IMAGE_FAILURE = 'GET_RANDOM_IMAGE_FAILURE';

export const GET_DOG_BY_BREED = 'GET_DOG_BY_BREED';
export const GET_DOG_BY_BREED_SUCCESS = 'GET_DOG_BY_BREED_SUCCESS';
export const GET_DOG_BY_BREED_FAILURE = 'GET_DOG_BY_BREED_FAILURE';

export const GET_BREED_DATA = 'GET_BREED_DATA';
export const GET_BREED_DATA_SUCCESS = 'GET_BREED_DATA_SUCCESS';
export const GET_BREED_DATA_FAILURE = 'GET_BREED_DATA_FAILURE';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

export const GET_BREEDLIST = 'GET_BREEDLIST';
export const GET_BREEDLIST_SUCCESS = 'GET_BREEDLIST_SUCCESS';
export const GET_BREEDLIST_FAILURE = 'GET_BREEDLIST_FAILURE';

